import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import './kingdom-city-kit.css';

type KitAsset = { assetId:string; displayName:string; format:string; viewerUrl?:string; sourceArchive:string; sourceEntry:string; styleGroup:string; materialFamilies:string[]; validationStatus:string; scaleStatus:string; collisionStatus:string; lodStatus:string; licenseStatus:string; metadata:{ triangleCount?:number; materialSlotCount?:number; category?:string; textureDependencies?:string[]; boundingBox?:{min:number[];max:number[]} } };
const stage='/dev-assets/kingdom-city-kit-v1/';
const viewport=document.querySelector<HTMLElement>('#viewport')!;
const status=document.querySelector<HTMLElement>('#status')!;
const stats=document.querySelector<HTMLElement>('#stats')!;
const list=document.querySelector<HTMLElement>('#asset-list')!;
const detail=document.querySelector<HTMLElement>('#asset-detail')!;
const scene=new THREE.Scene();scene.background=new THREE.Color('#152535');
const camera=new THREE.PerspectiveCamera(42,1,.01,1000);camera.position.set(5,3.2,6);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;viewport.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,1,0);
const loader=new GLTFLoader();const root=new THREE.Group();scene.add(root);
const assetGroup=new THREE.Group();root.add(assetGroup);const proxyGroup=new THREE.Group();root.add(proxyGroup);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x384a40,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;root.add(ground);
const grid=new THREE.GridHelper(30,30,0x6b8490,0x304657);grid.position.y=.002;root.add(grid);
scene.add(new THREE.HemisphereLight(0xa9d7ff,0x263229,2.1));const key=new THREE.DirectionalLight(0xffe8c5,3);key.position.set(4,8,5);key.castShadow=true;scene.add(key);
let proxy:THREE.Object3D|null=null;let bounds:THREE.Box3Helper|null=null;let current:KitAsset|null=null;let filtered:KitAsset[]=[];let all:KitAsset[]=[];let wire=false;
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();renderer.setSize(w,h,false)}addEventListener('resize',resize);resize();
function fitCamera(obj:THREE.Object3D){const box=new THREE.Box3().setFromObject(obj);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());const radius=Math.max(size.x,size.y,size.z,.8);controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(radius*1.6,radius*1.05,radius*1.8));camera.near=Math.max(radius/1000,.01);camera.far=Math.max(radius*20,100);camera.updateProjectionMatrix();controls.update()}
function clearAsset(){while(assetGroup.children.length){const o=assetGroup.children.pop()!;o.traverse(n=>{const m=n as THREE.Mesh;m.geometry?.dispose();const mats=Array.isArray(m.material)?m.material:m.material?[m.material]:[];mats.forEach(x=>x.dispose())})}if(bounds){root.remove(bounds);bounds=null}}
function createProxy(){if(proxy)return;loader.load('/assets/characters/male-revision-02/male-revision-02.glb',(g)=>{proxy=g.scene;proxyGroup.add(proxy!);proxy!.traverse(n=>{const m=n as THREE.Mesh;m.castShadow=true});const b=new THREE.Box3().setFromObject(proxy!);const h=b.max.y-b.min.y;if(h>0)proxy!.scale.setScalar(1.75/h);proxy!.position.set(0,0,0);proxyGroup.visible=(document.querySelector<HTMLInputElement>('#proxy')!).checked},()=>{createFallbackProxy()})}
function createFallbackProxy(){const material=new THREE.MeshStandardMaterial({color:0x5ea5c5,roughness:.8});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.26,1.2,6,12),material);body.position.y=1.0;proxy=new THREE.Group();proxy.add(body);proxyGroup.add(proxy);proxyGroup.visible=true}
function addProxyBeside(obj:THREE.Object3D){if(!proxy)return;const b=new THREE.Box3().setFromObject(obj);const size=b.getSize(new THREE.Vector3());proxyGroup.position.set(b.max.x+Math.max(size.x*.35,1.5),0,b.min.z);}
function setDetail(a:KitAsset,actual?:{box:THREE.Box3;materials:number;textures:string[]}){const m=a.metadata;const dims=actual?actual.box.getSize(new THREE.Vector3()):null;const dimText=dims?`${dims.x.toFixed(2)} × ${dims.y.toFixed(2)} × ${dims.z.toFixed(2)} units`:m.boundingBox&&m.boundingBox.min?`${(m.boundingBox.max[0]-m.boundingBox.min[0]).toFixed(2)} × ${(m.boundingBox.max[1]-m.boundingBox.min[1]).toFixed(2)} × ${(m.boundingBox.max[2]-m.boundingBox.min[2]).toFixed(2)} units`:'UNKNOWN';const tex=actual?.textures?.length?actual.textures.join(', '):(m.textureDependencies?.length?m.textureDependencies.join(', '):'No readable dependency');detail.innerHTML=`<h2>${a.displayName}</h2><div>${a.assetId} · <span class="${a.format==='GLTF'?'status-ok':'status-hold'}">${a.validationStatus}</span></div><div class="detail-grid"><div class="detail-cell"><b>Format</b><span>${a.format}</span></div><div class="detail-cell"><b>Dimensions</b><span>${dimText}</span></div><div class="detail-cell"><b>Triangles</b><span>${m.triangleCount??'UNKNOWN'}</span></div><div class="detail-cell"><b>Materials</b><span>${actual?.materials??m.materialSlotCount??'UNKNOWN'}</span></div><div class="detail-cell"><b>Scale</b><span>${a.scaleStatus}</span></div><div class="detail-cell"><b>Style</b><span>${a.styleGroup}</span></div><div class="detail-cell"><b>Collision / LOD</b><span>${a.collisionStatus} / ${a.lodStatus}</span></div><div class="detail-cell"><b>License</b><span>${a.licenseStatus}</span></div></div><div class="asset-id">Source: ${a.sourceArchive}<br/>Entry: ${a.sourceEntry}<br/>Textures: ${tex}</div>`}
function updateCards(){const q=(document.querySelector<HTMLInputElement>('#search')!).value.toLowerCase();const style=((document.querySelector('#style-filter') as unknown as HTMLSelectElement)).value;const cat=((document.querySelector('#category-filter') as unknown as HTMLSelectElement)).value;const only=(document.querySelector<HTMLInputElement>('#renderable-only')!).checked;filtered=all.filter(a=>(!q||(a.assetId+' '+a.displayName).toLowerCase().includes(q))&&(style==='all'||a.styleGroup===style)&&(cat==='all'||a.metadata.category===cat)&&(!only||a.format==='GLTF'));list.innerHTML='';filtered.forEach(a=>{const el=document.createElement('div');el.className='asset-card'+(current?.assetId===a.assetId?' selected':'');el.innerHTML=`<span class="dot ${a.format==='GLTF'?'':'hold'}"></span><div><div class="asset-name">${a.displayName}</div><div class="asset-id">${a.assetId}</div></div><div class="asset-meta">${a.format}<br/>${a.metadata.triangleCount??'—'} tri</div>`;el.onclick=()=>selectAsset(a);list.appendChild(el)})}
async function selectAsset(a:KitAsset){current=a;updateCards();clearAsset();proxyGroup.position.set(0,0,0);if(a.format!=='GLTF'){setDetail(a);status.textContent=`${a.displayName}: conversion required before 3D preview`;fitCamera(ground);return}status.textContent=`Loading ${a.displayName}…`;try{const g=await loader.loadAsync(a.viewerUrl!);assetGroup.add(g.scene);g.scene.traverse(n=>{const m=n as THREE.Mesh;m.castShadow=true;m.receiveShadow=true;if(wire&&m.material){const mats=Array.isArray(m.material)?m.material:m.material?[m.material]:[];mats.forEach(x=>{if ('wireframe' in x) x.wireframe=true})}});const box=new THREE.Box3().setFromObject(g.scene);bounds=new THREE.Box3Helper(box,0x8ec9e5);bounds.visible=(document.querySelector<HTMLInputElement>('#bounds')!).checked;root.add(bounds);addProxyBeside(g.scene);proxyGroup.visible=(document.querySelector<HTMLInputElement>('#proxy')!).checked;fitCamera(g.scene);const mats=new Set<THREE.Material>();const textures:string[]=[];g.scene.traverse(n=>{const m=n as THREE.Mesh;if(m.material){for(const mm of (Array.isArray(m.material)?m.material:[m.material])){mats.add(mm);const x=mm as THREE.MeshStandardMaterial;if(x.map?.image)textures.push(`${x.map.name||'albedo'} ${x.map.image.width}×${x.map.image.height}`)}}});setDetail(a,{box,materials:mats.size,textures:[...new Set(textures)]});status.textContent=`Rendered ${a.displayName}` }catch(e){setDetail(a);status.textContent=`Render error: ${(e as Error).message}`;console.error(e)}}
async function main(){const response=await fetch(stage+'metadata/kit-manifest.json');if(!response.ok)throw new Error(`Manifest ${response.status}`);const manifest=await response.json() as {assets:KitAsset[];shortlistCount:number;renderableCount:number;conversionRequiredCount:number};all=manifest.assets;const styleSelect=(document.querySelector('#style-filter') as unknown as HTMLSelectElement);[...new Set(all.map((a:KitAsset)=>a.styleGroup))].sort((a,b)=>String(a).localeCompare(String(b))).forEach(v=>styleSelect.insertAdjacentHTML('beforeend',`<option value="${v}">${v}</option>`));const catSelect=(document.querySelector('#category-filter') as unknown as HTMLSelectElement);[...new Set(all.map((a:KitAsset)=>a.metadata.category).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b))).forEach(v=>catSelect.insertAdjacentHTML('beforeend',`<option value="${v}">${v}</option>`));stats.textContent=`${manifest.shortlistCount} entries · ${manifest.renderableCount} GLTF · ${manifest.conversionRequiredCount} HOLD`;createProxy();['search','style-filter','category-filter','renderable-only'].forEach(id=>document.querySelector(`#${id}`)!.addEventListener('input',updateCards));updateCards();if(all[0])await selectAsset(all[0]);Object.assign(window, { __kingdomKit:{manifest,selectAsset,all}})}main().catch(e=>{status.textContent=`ERROR: ${(e as Error).message}`;console.error(e)});
document.querySelector('#reset-camera')!.addEventListener('click',()=>{if(current){const obj=assetGroup.children[0];if(obj)fitCamera(obj)}});document.querySelector<HTMLInputElement>('#proxy')!.addEventListener('change',e=>proxyGroup.visible=(e.target as HTMLInputElement).checked);document.querySelector<HTMLInputElement>('#ground')!.addEventListener('change',e=>{const v=(e.target as HTMLInputElement).checked;ground.visible=v;grid.visible=v});document.querySelector<HTMLInputElement>('#bounds')!.addEventListener('change',e=>{if(bounds)bounds.visible=(e.target as HTMLInputElement).checked});document.querySelector<HTMLInputElement>('#wireframe')!.addEventListener('change',e=>{wire=(e.target as HTMLInputElement).checked;assetGroup.traverse(n=>{const m=n as THREE.Mesh;if(m.material){const ms=Array.isArray(m.material)?m.material:m.material?[m.material]:[];ms.forEach(x=>{if ('wireframe' in x) x.wireframe=wire})}})});
function frame(){requestAnimationFrame(frame);controls.update();renderer.render(scene,camera)}frame();
