// @ts-nocheck — isolated browser-only contact-sheet entry; production source is unaffected.
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import './kingdom-city-kit-sheets.css';
type A={assetId:string;displayName:string;format:string;viewerUrl?:string;styleGroup:string;metadata:any};
const stage='/dev-assets/kingdom-city-kit-v1/';const status=document.querySelector('#status')!;const root=document.querySelector('#sheets')!;const loader=new GLTFLoader();
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(240,150,false);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color('#162738');scene.add(new THREE.HemisphereLight(0xb9dcff,0x273029,2));const light=new THREE.DirectionalLight(0xffe4bf,3);light.position.set(4,7,5);scene.add(light);const ground=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.MeshStandardMaterial({color:0x384941,roughness:1}));ground.rotation.x=-Math.PI/2;scene.add(ground);const camera=new THREE.PerspectiveCamera(38,240/150,.01,1000);
function dispose(o:THREE.Object3D){o.traverse(n=>{const m=n as THREE.Mesh;m.geometry?.dispose();const ms=Array.isArray(m.material)?m.material:m.material?[m.material]:[];ms.forEach(x=>x.dispose())})}
function card(a:A){const el=document.createElement('article');el.className='card';const title=document.createElement('div');title.className='copy';title.innerHTML=`<div class="name">${a.displayName}</div><div class="meta">${a.assetId} · ${a.format} · ${a.metadata.triangleCount??'unknown'} tri</div>`;if(a.format!=='GLTF'){const hold=document.createElement('div');hold.className='hold';hold.textContent='HOLD · BLEND conversion required';el.append(hold,title);return el}const canvas=document.createElement('canvas');canvas.width=240;canvas.height=150;el.append(canvas,title);render(a,canvas).catch(e=>{title.querySelector('.meta')!.textContent=`Render failed: ${e.message}`});return el}
async function render(a:A,canvas:HTMLCanvasElement){const g=await loader.loadAsync(a.viewerUrl!);const box=new THREE.Box3().setFromObject(g.scene);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());g.scene.position.sub(center);scene.add(g.scene);const radius=Math.max(size.x,size.y,size.z,.8);camera.position.set(radius*1.45,radius*.95,radius*1.55);camera.lookAt(0,Math.max(size.y*.15,0),0);renderer.render(scene,camera);canvas.getContext('2d')!.drawImage(renderer.domElement,0,0,240,150);scene.remove(g.scene);dispose(g.scene)}
async function main(){const m=await fetch(stage+'metadata/kit-manifest.json').then(r=>r.json());const grouped=new Map<string,A[]>();for(const a of m.assets){if(!grouped.has(a.styleGroup))grouped.set(a.styleGroup,[]);grouped.get(a.styleGroup)!.push(a)}for(const [group,assets] of grouped){const sec=document.createElement('section');sec.className='sheet';sec.innerHTML=`<h2>${group} · ${assets.length} assets</h2>`;const grid=document.createElement('div');grid.className='grid';sec.append(grid);root.append(sec);for(const a of assets)grid.append(card(a))}status.textContent=`${m.shortlistCount} shortlist entries · ${m.renderableCount} GLTF previews · ${m.conversionRequiredCount} BLEND HOLD`}
main().catch(e=>{status.textContent=`ERROR: ${e.message}`;console.error(e)});
