/** Presentation metadata only; progression and effects remain in the skill registry. */
export const SKILL_VISUALS = {
  'v2-thief-quick-stab':['dagger','steel'],
  'v2-thief-slipstep':['dash','dagger'],
  'v2-thief-mark-prey':['target','dagger'],
  'v2-thief-smoke-veil':['vanish','mark'],
  'v2-thief-twin-fang':['daggers','fracture'],
  'v2-thief-crippling-cut':['dagger','chains'],
  'v2-thief-venom-edge':['dagger','poison'],
  'v2-thief-evasive-feint':['footprints','eye'],
  'v2-thief-shadow-lunge':['dash','moon'],
  'v2-thief-marked-strike':['dagger','mark'],
  'v2-thief-blade-flurry':['daggers','spiral'],
  'v2-thief-silent-opening':['dagger','moon'],
  'v2-thief-rear-rend':['dagger','skull'],
  'v2-thief-disengage':['footprints','chains'],
  'v2-thief-weakpoint-assault':['daggers','target'],
  'v2-thief-instinct':['eye','dagger'],
  'v2-thief-agile-conditioning':['heart','dagger'],
  'v2-thief-dagger-discipline':['anvil','dagger'],
  'v2-thief-keen-instinct':['eye','speed'],
  'v2-thief-shadow-discipline':['vanish','steel'],
  'v2-thief-dual-dagger-familiarity':['daggers','anvil'],
  'v2-thief-mark-expertise':['target','mark'],
  'v2-thief-fleet-footing':['footprints','speed'],
  'v2-thief-venomcraft':['book','poison'],
  'v2-thief-rear-awareness':['eye','fracture'],
  'v2-thief-opportunist':['eye','chains'],
  'v2-thief-twin-edge-control':['daggers','eye'],
  'v2-thief-rapid-technique':['daggers','pulse'],
  'v2-thief-evasive-instinct':['heart','speed'],
  'v2-thief-silent-opportunity':['vanish','target'],
  'v2-warrior-strike': ['sword','steel'],
  'v2-warrior-iron-charge': ['dash','steel'],
  'v2-warrior-sweeping-slash': ['sword','spiral'],
  'v2-warrior-guard-stance': ['guard','steel'],
  'v2-warrior-rising-slash': ['sword','earth'],
  'v2-warrior-armor-breaker': ['sword','fracture'],
  'v2-warrior-battle-cry': ['hand','steel'],
  'v2-warrior-counter-slash': ['sword','parry'],
  'v2-warrior-ground-breaker': ['shockwave','earth'],
  'v2-warrior-battle-focus': ['eye','steel'],
  'v2-warrior-severing-arc': ['sword','burst'],
  'v2-warrior-relentless-assault': ['swords','speed'],
  'v2-warrior-unbroken-stance': ['guard','earth'],
  'v2-warrior-iron-reversal': ['swords','parry'],
  'v2-warrior-crushing-finale': ['hammer','skull'],
  'v2-warrior-awakening': ['sword','crown'],
  'v2-warrior-conditioning': ['heart','steel'],
  'v2-warrior-weapon-discipline': ['anvil','sword'],
  'v2-warrior-firm-footing': ['footprints','earth'],
  'v2-warrior-guard-training': ['guard','shield'],
  'v2-warrior-combat-instinct': ['eye','sword'],
  'v2-warrior-heavy-impact': ['hammer','earth'],
  'v2-warrior-battle-momentum': ['pulse','steel'],
  'v2-warrior-counter-training': ['anvil','parry'],
  'v2-warrior-adrenaline': ['heart','flame'],
  'v2-warrior-indomitable-will': ['guard','crown'],
  'v2-warrior-great-weapon-familiarity': ['sword','anvil'],
  'v2-warrior-great-weapon-momentum': ['hammer','speed'],
  'v2-warrior-twin-blade-familiarity': ['swords','steel'],
  'v2-warrior-twin-blade-rhythm': ['swords','pulse'],
  'fajar-step': ['dash', 'dawn'],
  'fajar-strike': ['sword', 'dawn'],
  'guard-stance': ['guard', 'dawn'],
  'nova-fajar': ['burst', 'dawn'],
  'warrior-breaker': ['hammer', 'impact'],
  'warrior-charge': ['dash', 'sword'],
  'warrior-guard': ['shield', 'steel'],
  'warrior-awakening': ['swords', 'flame'],
  'rogue-step': ['footprints', 'moon'],
  'rogue-flurry': ['daggers', 'speed'],
  'rogue-vanish': ['vanish', 'moon'],
  'rogue-awakening': ['swords', 'moon'],
  'hunter-aim': ['target', 'arrow'],
  'hunter-volley': ['arrows', 'leaf'],
  'hunter-bind': ['arrow', 'chains'],
  'hunter-awakening': ['arrows', 'burst'],
  'wizard-bolt': ['bolt', 'arcane'],
  'wizard-circle': ['orbit', 'arcane'],
  'wizard-chain': ['chains', 'bolt'],
  'wizard-awakening': ['meteor', 'arcane'],
  'acolyte-blessing': ['hand', 'dawn'],
  'acolyte-heal': ['heart', 'dawn'],
  'acolyte-barrier': ['shield', 'dawn'],
  'acolyte-awakening': ['burst', 'heart'],
  'gatotkaca-1': ['leap', 'bolt'],
  'gatotkaca-2': ['fist', 'earth'],
  'gatotkaca-3': ['shockwave', 'bolt'],
  'gatotkaca-4': ['fist', 'storm'],
  'garda-1': ['shield', 'dash'],
  'garda-2': ['hammer', 'fracture'],
  'garda-3': ['castle', 'shield'],
  'garda-4': ['shield', 'heart'],
  'caroq-1': ['footprints', 'dagger'],
  'caroq-2': ['daggers', 'storm'],
  'caroq-3': ['vanish', 'dagger'],
  'caroq-4': ['swords', 'spiral'],
  'anom-1': ['eye', 'mark'],
  'anom-2': ['swords', 'mark'],
  'anom-3': ['vanish', 'eye'],
  'anom-4': ['sword', 'skull'],
  'srikandi-1': ['target', 'eye'],
  'srikandi-2': ['arrows', 'dawn'],
  'srikandi-3': ['arrow', 'snow'],
  'srikandi-4': ['arrows', 'storm'],
  'jagawana-1': ['trap', 'root'],
  'jagawana-2': ['arrow', 'poison'],
  'jagawana-3': ['net', 'leaf'],
  'jagawana-4': ['forest', 'trap'],
  'resi-1': ['pentagon', 'flame'],
  'resi-2': ['orbit', 'flame'],
  'resi-3': ['chains', 'flame'],
  'resi-4': ['pentagon', 'burst'],
  'pujangga-1': ['scroll', 'mark'],
  'pujangga-2': ['scroll', 'skull'],
  'pujangga-3': ['masks', 'moon'],
  'pujangga-4': ['music', 'skull'],
  'pandita-1': ['hand', 'heart'],
  'pandita-2': ['heart', 'cross'],
  'pandita-3': ['shield', 'cross'],
  'pandita-4': ['prayer', 'dawn'],
  'bajra-1': ['fist', 'dawn'],
  'bajra-2': ['orbit', 'dawn'],
  'bajra-3': ['hand', 'parry'],
  'bajra-4': ['burst', 'fist'],
  'adventurer-resolve': ['compass', 'dawn'],
  'warrior-foundation': ['anvil', 'steel'],
  'rogue-foundation': ['eye', 'moon'],
  'hunter-foundation': ['eye', 'arrow'],
  'wizard-foundation': ['book', 'arcane'],
  'acolyte-foundation': ['heart', 'hand'],
  'iron-muscle': ['anvil', 'bolt'],
  gatekeeper: ['castle', 'steel'],
  'caroq-rhythm': ['pulse', 'dagger'],
  'execution-instinct': ['eye', 'skull'],
  'srikandi-eye': ['eye', 'dawn'],
  'forest-warden': ['forest', 'leaf'],
  'five-elements': ['pentagon', 'orbit'],
  'mantra-lore': ['book', 'scroll'],
  compassion: ['heart', 'prayer'],
  'dharma-will': ['fist', 'cross'],
  'gatotkaca-capstone': ['fist', 'crown'],
  'garda-capstone': ['castle', 'crown'],
  'caroq-capstone': ['daggers', 'crown'],
  'anom-capstone': ['skull', 'crown'],
  'srikandi-capstone': ['target', 'crown'],
  'jagawana-capstone': ['forest', 'crown'],
  'resi-capstone': ['pentagon', 'crown'],
  'pujangga-capstone': ['scroll', 'crown'],
  'pandita-capstone': ['prayer', 'crown'],
  'bajra-capstone': ['burst', 'crown'],
} as const;
export type SkillGlyph =
  (typeof SKILL_VISUALS)[keyof typeof SKILL_VISUALS][number];
