"""Publish local evidence/report only; never modifies game or Blender assets."""
import json,math,html,shutil
from pathlib import Path
R=Path(__file__).resolve().parents[1];D=R/'dev-prototypes/mahkota-fajar-stage03-v1';E=D/'evidence'
M=json.loads((D/'assets/manifest.json').read_text());B=json.loads((E/'final-browser.json').read_text());V=json.loads((E/'polish-final/state.json').read_text());S=json.loads((E/'polish-measurements.json').read_text());C=json.loads((E/'polish-camera/results.json').read_text());P=json.loads((E/'pre-polish/final-browser.json').read_text())
buildings=[
('guild','Grand Hall',(480,0,250,205),'Portal berlapis, kolom/pinnacle, dormer, rose tracery dan trim kuningan ditambahkan.','Siluet lebih tinggi dan berat daripada referensi; atap pusat masih satu massa dominan. Fasad batu terlalu seragam, jendela hijau datar, ukiran dan kedalaman portal belum sehalus target. Proporsi footprint lama dipertahankan; lanskap depan lebih jarang.'),
('job','Job Change Hall',(750,80,240,210),'Kubah kontinu dengan rusuk emas, lantern sejajar, cornice, portal/kolom, dan gable sayap dipulihkan.','Kubah dan lantern lebih sederhana; ritme jendela lurus, relief portal dan trim lebih sedikit. Material batu lebih homogen, biru lebih gelap, sayap lebih kaku; taman belum selapis referensi.'),
('training','Training Yard',(180,122,300,180),'Dummy berhelm/perisai, bekas latihan, rak dan shelter dipertahankan; stasiun lengkap dipertahankan pada LOD jauh.','Siluet pagar/pintu dan shelter lebih geometris; kayu/atap belum memiliki keausan target. Lapangan terasa lebih kosong dan bukaan pagar lebih lebar. Tidak ada fasad/jendela tertutup untuk dibandingkan.'),
('merchant','Merchant',(70,255,215,140),'Penanda koin dan display; produce disesuaikan ke counter 1,1 unit; awning biru-putih/dormer dipertahankan.','Massa tiga tingkat lebih tinggi daripada toko kompak referensi. Atap/awning lebih lurus, fasad dan portal kurang kaya, jendela datar dan trim minim; kayu terlalu teratur, isi pasar dan taman lebih jarang.'),
('potion','Potion Shop',(280,312,170,110),'Penanda botol, botol biru di counter, herba dan kanopi membedakan toko.','Atap merah dan bentuk silang cocok secara identitas; massa masih lebih tinggi. Fasad/portal, bingkai jendela dan trim sederhana, kanopi pucat, botol kurang beragam; rak dan lanskap lebih jarang.'),
('weapon','Weapon Shop',(85,410,170,140),'Penanda pedang silang, rak dan display; tinggi pintu serta counter dikoreksi.','Siluet masih rumah tiga tingkat dengan atap pelana sederhana. Portal/overhang, jendela dan trim belum serinci referensi; warna merah-kayu cocok tetapi material bersih. Tampilan senjata kecil pada pandangan jauh dan halaman lapang.'),
('armor','Armor Shop',(265,430,170,130),'Penanda perisai, breastplate/helm pada stand dan identitas fasad biru dipertegas.','Gable, portal dan trim emas belum seornamental referensi. Fasad/jendela tetap sederhana, armor lebih gelap; proporsi massa lebih tinggi, halaman/taman lebih kosong. Atap biru mempertahankan palet tetapi detail masih berulang.'),
('forge','Blacksmith',(750,270,300,190),'Open forge, ember bed, soot lintel, tool rack; anvil/workbench diskalakan, pelat cerobong salah posisi dihapus.','Cerobong masih terlalu dominan/kotak. Atap, portal tungku, bukaan dan struktur kayu lebih sederhana; emissive lebih terang dan kurang volumetrik. Material jelaga/metal, trim, keausan tanah dan kepadatan alat belum setara; jendela bukan fokus struktur terbuka.'),
('bank','Storage / Bank',(760,430,250,150),'Portal batu/kuningan, buttress, dormer dan simbol koin memperkuat identitas bank.','Siluet lebih tinggi/kaku; gable depan, fasad, portal dan jendela belum memiliki relief target. Trim emas lebih sedikit, batu homogen dan biru lebih gelap. Struktur samping berupa kanopi sederhana; halaman lebih luas/kosong.'),
('inn','Inn / Tavern',(205,570,270,140),'Kanopi linen, penanda mug, meja 0,9 dan kursi 0,55 unit; tableware tidak melayang lagi.','Massa dua tingkat lebih besar daripada referensi. Atap, fasad/portal, jendela dan trim masih berpola sederhana; warna kayu/terracotta sesuai keluarga tetapi detail hangat kurang. Seating persegi belum menyerupai meja-payung bundar dan taman lebih jarang.'),
('residential','Residential A / B',(730,570,255,150),'Pintu, window box/bunga dan detail domestik diperbaiki; Residence B tidak dipindah.','Siluet dan atap tetap lebih tegak/geometris; fasad timber, portal, jendela serta trim lebih sederhana. Material bersih, warna merah/terracotta sesuai tetapi kebun dan pagar domestik belum sekaya target. Proporsi rumah tetap mengikuti fondasi yang disetujui.'),
('center','Central Plaza / Quest Board',(470,320,245,200),'Patung patina, cincin biru/kuningan, riak air, notices dengan glyph dan seal pada ketinggian baca.','Patung lebih kaku dan besar secara visual; air/pancuran belum lembut seperti referensi. Komposisi ring dan jalur tetap, planter lebih geometris. Quest frame/kanopi/jendela tidak relevan sebagai bangunan; detail papan masih simbol tanpa teks gameplay final.'),
('warp','Warp Plaza',(485,570,225,175),'Kristal transparan/emissive terkendali, facet edges, inti, rune dan riser 0,1201 unit.','Kristal masih prisma memanjang; glow tidak memakai bloom/refraction. Pedestal/ring lebih sederhana, batu dan trim kurang halus, vegetasi/banner lebih jarang. Portal perjalanan belum diaktifkan sesuai scope; fasad/jendela tidak berlaku.'),
('edge','Wall / Island Edge',(890,650,215,265),'Batu berlapis dibulatkan, palet batu dipertahankan, warna/depth air dan pecahan foam; ring/gate tetap.','Tebing masih berundak/geometris dibanding batu organik referensi. Air statis dan foam berupa strip; menara/cap, relief tembok dan trim lebih sederhana. Tidak ada vegetasi rimbun di luar; lingkungan tetap dibatasi 250×250.'),
]
views=[('top','Top Down'),('overview','High Aerial 3/4'),('front','Central Plaza → Grand Hall'),('guild','Grand Hall'),('job','Job Change Hall'),('training','Training Yard'),('merchant','Merchant'),('forge','Blacksmith'),('bank','Storage / Bank'),('inn','Inn / Tavern'),('residential','Residential'),('warp','Warp Plaza'),('edge','Wall / Island Edge'),('street','Player-eye Street View')]
esc=html.escape
out=['<!doctype html><html lang="id"><meta charset="utf-8"><title>LUMENFALL — Visual Polish</title><style>body{background:#101c22;color:#eee;font:16px/1.5 system-ui;margin:0;padding:32px}main{max-width:1450px;margin:auto}h1,h2{color:#e3cc90}section{border-top:1px solid #48606a;padding:24px 0}.pair{display:grid;grid-template-columns:1fr 2fr;gap:16px}img,svg{width:100%;background:#203039}small{color:#b9c9cc}a{color:#b9dcff}.views{display:grid;grid-template-columns:1fr 1fr;gap:18px}summary{cursor:pointer}figure{margin:0}p{max-width:1100px} @media(max-width:850px){.pair,.views{grid-template-columns:1fr}}</style><main><h1>LUMENFALL Stage03 — Reference vs In-game</h1><p>Development candidate. Hasil pemolesan, bukan klaim identik dengan ilustrasi. Semua gambar kanan berasal dari runtime kandidat 1920×1080, DPR 1. Referensi kiri ditampilkan melalui viewport SVG tanpa mengubah berkas asli.</p><p><a href="reference-blueprint.png">Buka blueprint lengkap</a> · <a href="final-browser.json">Regresi/performa</a> · <a href="polish-measurements.json">Pengukuran</a> · <a href="polish-camera/results.json">Kamera</a></p>']
for key,title,roi,change,deviation in buildings:
 out.append(f'<section id="{key}"><h2>{esc(title)}</h2><div class="pair"><figure><figcaption>REFERENCE</figcaption><svg viewBox="{" ".join(map(str,roi))}" xmlns="http://www.w3.org/2000/svg"><image href="reference-blueprint.png" width="1450" height="1088"/></svg></figure><figure><figcaption>FINAL IN-GAME</figcaption><a href="polish-final/{key}.png"><img loading="lazy" src="polish-final/{key}.png"></a></figure></div><p><b>Perubahan:</b> {esc(change)}</p><p><b>Perbedaan tersisa:</b> {esc(deviation)}</p>')
 before=E/'pre-polish'/('runtime-'+key+'.png')
 if before.exists():out.append(f'<details><summary>Baseline sebelum polish</summary><img loading="lazy" src="pre-polish/runtime-{key}.png"></details>')
 out.append('</section>')
out.append('<section><h2>14 sudut perbandingan wajib</h2><div class="views">')
for key,title in views:out.append(f'<figure><figcaption>{esc(title)}</figcaption><a href="polish-final/{key}.png"><img loading="lazy" src="polish-final/{key}.png"></a></figure>')
out.append('</div><p>Perbedaan yang berlaku untuk seluruh kota: komposisi lebih lapang dan teratur; warna/material lebih seragam, foliage masih bergaya low-poly. LOD dan instancing dipertahankan untuk anggaran performa. Interior bangunan tertutup tidak dibuat.</p></section></main></html>')
(E/'polish-comparison.html').write_text(''.join(out),encoding='utf-8')
old=E/'comparison.html';backup=E/'pre-polish/comparison.html'
if old.exists() and not backup.exists():shutil.copy2(old,backup)
old.write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=polish-comparison.html"><title>LUMENFALL visual comparison</title><a href="polish-comparison.html">Buka perbandingan visual Stage03 terbaru</a>',encoding='utf-8')
def maximum(data,key):return max(r[key] for r in data['routes'])
avg=sum(r['frameAverage']*r['frames'] for r in B['routes'])/sum(r['frames'] for r in B['routes'])
metrics=V['state']['metrics'];mb=lambda x:f'{x/1048576:.2f} MiB'
rows=[('p95 terburuk / rute',f"{maximum(P,'frameP95'):.2f} ms",f"{maximum(B,'frameP95'):.2f} ms"),('Rata-rata tertimbang frame','Tidak direkam',f'{avg:.2f} ms'),('Draw calls traversal, termasuk shadow',str(maximum(P,'maxDraws')),str(maximum(B,'maxDraws'))),('Triangulasi traversal, primary',str(maximum(P,'maxPrimaryTriangles')),str(maximum(B,'maxPrimaryTriangles'))),('Triangulasi traversal + shadow',str(maximum(P,'maxTriangles')),str(maximum(B,'maxTriangles'))),('Resident seluruh LOD','778021',str(metrics['triangles'])),('Material aktif','20',str(metrics['materials'])),('Memori tekstur estimasi RGBA+mip','101.33 MiB',mb(metrics['textures'])),('Payload gzip + manifest','24.22 MiB',mb(M['payloadBytes']+(D/'assets/manifest.json').stat().st_size))]
doc=['# LUMENFALL Stage03 — Visual Polish\n','Status: kandidat development sudah dipoles dan diuji ulang. Kesetiaan visual meningkat pada landmark dan identitas layanan, tetapi belum identik dengan referensi. Detail yang belum menyamai target dicatat per bangunan. Tidak dipublikasikan.\n',f"Map: `{M['mapId']}`. Working Blender: `{D/'source/LUMENFALL_Stage03_Runtime_Working.blend'}`. Backup sebelum polish: `source/LUMENFALL_Stage03_PrePolish.blend`.\n",'## Perubahan aset dan bangunan\n','Daftar objek lengkap dan fase perubahan: [polish-object-changes.json](../dev-prototypes/mahkota-fajar-stage03-v1/evidence/polish-object-changes.json). Stable IDs, district grouping, anchor dan arsitektur hybrid dipertahankan.\n','| Bangunan | Perubahan |\n|---|---|']
for key,title,roi,change,deviation in buildings:doc.append(f'| {title} | {change} |')
doc+=['\nVegetasi: 70 tree placements memakai tiga modul (bulat, melebar, ramping), cabang/cluster daun baru; 362 shrub placements dipertahankan dengan modul clump yang disederhanakan. Sector instancing dan LOD 35/75 dipertahankan, shrub kecil cull 60. Arsitektur tidak ditutupi tambahan hutan.\n','Material: 6 keluarga bake lama dipertahankan; tambahan 2 permukaan warna procedural tiling 1K (terracotta, slate) memakai normal/ORM bersama. Eksperimen tekstur ground/rock dibatalkan setelah review top-down; palet baseline dipulihkan. Bukan bake AO unik per bangunan; AO lama/vertex-color tetap dan tidak diklaim sebagai bake final baru. Tidak memakai refraction mahal.\n','## Pengukuran dan preservasi\n',f"Sumber asli SHA256 tetap `{S['sourceHash']}`. Collision GLB tetap `{S['collisionAssetHash']}`. Residence B bounds identik: **{S['residenceBUnchanged']}**. Root scale {B['checks']['rootScale']}; player {B['checks']['playerHeight']} unit; bounds {B['checks']['bounds']}.\n",'| Elemen | Hasil terukur |\n|---|---|']
for kind in ['door','counter','table','stairs','road']:
 a=[x for x in S['measurements'] if x['kind']==kind]
 if kind=='door':value=f"{len(a)} contoh pintu tunggal; tinggi {min(x['height'] for x in a):.3f}, lebar minimum {min(x['width'] for x in a):.3f}. Lebar adalah projected XY span mesh, bukan sertifikasi bukaan interior."
 elif kind in ['counter','table']:value=f"{len(a)} contoh, tinggi {min(x['height'] for x in a):.3f}–{max(x['height'] for x in a):.3f} unit"
 elif kind=='stairs':value='; '.join(x['id']+': '+','.join(f'{r:.4f}' for r in sorted(set(round(v,4) for v in x['risers']))) for x in a)
 else:value=f"{len(a)} jalur, pemisahan curb minimum {min(x['minimumCurbSeparation'] for x in a):.3f} unit; batas curb bukan jaminan seluruh jalur bebas prop."
 doc.append(f'| {kind} | {value} |')
doc.append(f"| Service approach / interaksi | Minimum radius bebas di seluruh anchor {min(x['clearance'] for x in B['anchors']):.3f}; minimum lebar obstacle sepanjang 18 lintasan {min(x['minimumObstacleClearWidth'] for x in B['routes']):.3f} unit. |")
fence=[b for b in M['blockers'] if b['id'] in ['LF_Training_Yard_Timber_Rails0','LF_Training_Yard_Timber_Rails9']]
gap=min(math.dist(a,b) for a in fence[0]['points'] for b in fence[1]['points'])
doc.append(f'| Bukaan pagar Training | Jarak endpoint bagian rail terbuka {gap:.3f} unit; lintasan masuk yang diuji memiliki lebar obstacle minimum {min(r["minimumObstacleClearWidth"] for r in B["routes"] if r["target"]=="training"):.3f}. Bukan lebar seluruh court. |')
doc+=['\nPintu bangunan tetap tertutup. Pengukuran adalah contoh representatif dan dimensi visual; tidak mengklaim setiap jendela/detail telah diukur. Rute Grand Hall memiliki lebar minimum sekitar 5,08 pada approach, memenuhi service access ≥3; target ≥6 diperiksa pada curb jalan utama.\n','## Visual sweep dan kamera\n','Diperbaiki: floating tableware/produce/tools, ukuran meja-counter-anvil, pintu rendah/sempit, UV kosong, zero-area triangles, duplikasi facet Warp, gable Job yang hilang, pusat dome/lantern, pelat cerobong salah posisi, perpotongan roof/wood dikurangi, dan LOD dummy yang semula meninggalkan helm/perisai.\n',f"Pemeriksaan mesh final: {len(S['geometryIssues'])} masalah UV/nonfinite; {len(S['degenerateFaces'])} objek dengan triangle nol luas; {len(S['duplicateNewMeshes'])} duplikasi mesh polish dalam group sama. Screenshot inspeksi mencakup depan/samping dan sudut jalan; tidak mengklaim inspeksi manual setiap polygon atau seluruh interior.\n",f"Kamera: {sum(r['sampled'] for r in C['rows'])} sampel orbit, {sum(len(r['failures']) for r in C['rows'])} penetrasi proxy pada sampel. Mencakup semua 12 massa bangunan, belakang Grand Hall, anchor, jalan toko, tembok timur/barat dan Warp. {sum(r['skipped'] for r in C['rows'])} titik di kompleks Job dilewati karena titik fokus/tanah tidak valid; sisi lain diuji. Recovery menjauh monoton: {C['recovery']['monotonic']}; jarak akhir {C['recovery']['final']:.2f}. Proxy atap konservatif dapat menarik kamera lebih dekat daripada geometri visual sebenarnya.\n",'## Regresi dan performa\n',f"18 rute: **{sum(r['pass'] for r in B['routes'])}/18 lulus**, seluruhnya dijalankan ulang setelah perubahan. Unit collision 6/6 lulus. Typecheck seluruh proyek `tsc --noEmit`: lulus. Kesalahan `position` pada `kingdom-pilot-scene.ts` adalah anotasi tipe lama yang tidak mencantumkan data yang sudah dihasilkan; diperbaiki tanpa perubahan perilaku.\n",'| Metrik | Sebelum | Sesudah |\n|---|---|---|']
for row in rows:doc.append('| '+' | '.join(row)+' |')
doc.append(f"\nPerangkat: {B['checks']['hardware']['renderer']}; {B['checks']['hardware']['userAgent']}; viewport 1920×1080, DPR 1. Frame time adalah interval RAF end-to-end saat traversal, bukan GPU timestamp. p95 dilaporkan sebagai p95 terburuk per rute, bukan p95 gabungan. Pengukuran ini lokal, bukan jaminan perangkat lain.\n")
if V.get('viewMetrics'):doc.append(f"Maksimum dari 19 view review: {max(s['calls'] for s in V['viewMetrics'].values())} draw calls termasuk shadow.\n")
doc.append('| Rute | Arah | Jarak | Waktu jalan | Min. lebar | Avg / p95 ms | Draw calls |\n|---|---|---:|---:|---:|---:|---:|')
for r in B['routes']:doc.append(f"| Central ↔ {r['target']} | {'kembali' if r['reverse'] else 'pergi'} | {r['distance']:.2f} | {r['walkSeconds']:.2f} s | {r['minimumObstacleClearWidth']:.2f} | {r['frameAverage']:.2f} / {r['frameP95']:.2f} | {r['maxDraws']} |")
doc.append(f"\nGate/boundary/ramp/recovery/roof-ground separation/keyboard/spawn: `{ {k:v for k,v in B['checks'].items() if isinstance(v,bool)} }`. Error UI: {B['errorDisplayed']}; Retry: {B['retryPassed']}. Reload 3×: root children {[r['rootChildren'] for r in B['reload']]}, canvas {[r['canvases'] for r in B['reload']]}, renderer memory {[r['memory'] for r in B['reload']]}. Stabilitas ini bukan pembuktian heap leak semua browser.\n")
doc+=['## Perbandingan dan deviasi tersisa\n','[Galeri reference vs final in-game](../dev-prototypes/mahkota-fajar-stage03-v1/evidence/polish-comparison.html) memuat 14 view wajib, tambahan Potion/Weapon/Armor/Central/player, baseline bila tersedia, dan evaluasi silhouette, roof, facade, portal, windows, trim, material, color, proportion, environment.\n']
for key,title,roi,change,deviation in buildings:doc.append(f'- **{title}:** {deviation}')
doc+=['\nBatas visual yang masih terlihat: transisi strip pada beberapa atap/LOD, material berulang, taman rendah/jarang, air tanpa animasi arus, dan tebing belum organik. Tidak mengklaim reference fidelity penuh atau hasil siap produksi.\n','## Berkas dan cara menjalankan\n','Berkas runtime diperbarui: `tests/browser/mahkota-fajar-stage03-scene.ts`, `mahkota-fajar-stage03.ts`, `mahkota-fajar-stage03.html`; perbaikan tipe: `tests/browser/kingdom-pilot-scene.ts`. Script baru: `inspect-stage03-polish.py`, `polish-stage03-candidate.py`, `measure-stage03-polish.py`, `update-stage03-camera-wall.py`, `visual-stage03-polish.mjs`, `report-stage03-polish.py`. Script regresi `test-stage03-browser.mjs` ditambah average frame time. `lib/game/world.ts` dan production map tidak diubah.\n','Aset lokal: `source/*Runtime_Working.blend`, `assets/manifest.json`, affected raw GLB dan `assets/runtime/*.glb.gz`, dua color textures aktif baru. Struktur hybrid tetap shell + 8 district/LOD + 8 wall sectors + reusable modules + collision; manifest menyimpan placements, anchors, blockers, cameraVolumes/cameraWall, material/textures dan polish log. Folder development tetap diabaikan Git, bukan paket publish.\n','Dari root repository:\n\n```powershell\nnode node_modules/vite/bin/vite.js --config tests/browser/mahkota-fajar-stage03.vite.config.ts\n```\n\nBuka http://127.0.0.1:3013/tests/browser/mahkota-fajar-stage03.html . Tunggu status DEVELOPMENT CANDIDATE. Pilih WASD Player untuk berjalan; tombol view untuk review; F8 untuk Map Review. Bila ERROR, tekan Retry setelah penyebab asset diperbaiki. Tidak perlu mengganti map produksi.\n','Jangan jalankan ulang initial build/rescale untuk melihat kandidat ini. Pipeline polish bekerja pada turunan; beberapa koreksi in-place merupakan langkah migrasi satu kali, bukan resep rekonstruksi yang idempotent dari sembarang fase. Backup pre-polish tersedia untuk reproduksi berurutan.\n']
doc.append('Catatan review tambahan: bidang paving/terrain berbentuk segitiga masih terbaca pada top-down. Ini deviasi visual yang belum dirapikan, bukan klaim fidelity selesai penuh. `render-stage03-comparison.py` juga diperbarui dengan `--assemble-only` untuk merakit preview placement dalam working Blender; preview instances dikecualikan dari ekspor runtime.\n')
(R/'docs/LUMENFALL-Stage03-Visual-Polish.md').write_text('\n'.join(doc),encoding='utf-8')
(E/'polish-object-changes.json').write_text(json.dumps(M['polish'],indent=2),encoding='utf-8')
print('Report and reference gallery created')
